# Generated by Django 4.0 on 2022-01-03 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='neighbours',
            field=models.ManyToManyField(to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
